"""Unit tests for ModelToolCallingAgent loop."""

from __future__ import annotations

import asyncio
import datetime
import uuid

from flight_agent_evaluator.agent.loop import ModelToolCallingAgent
from flight_agent_evaluator.agent.model_client import ReplayModelClient
from flight_agent_evaluator.agent.prompt import get_default_prompt_policy
from flight_agent_evaluator.contracts.model import (
    AgentStopReason,
    AgentTask,
    ModelExchange,
    ModelRequest,
    ModelResponse,
    ModelToolCall,
)
from flight_agent_evaluator.engine.tool_executor import ToolExecutor
from flight_agent_evaluator.providers.fixture import FixtureFlightProvider
from flight_agent_evaluator.recording.journal import HashChainJournal
from flight_agent_evaluator.runtime.clock import DeterministicVirtualClock
from flight_agent_evaluator.runtime.context import RunContext
from flight_agent_evaluator.runtime.ids import DeterministicIdFactory
from flight_agent_evaluator.runtime.state import StateSnapshot
from flight_agent_evaluator.tools.base import build_default_registry


def _make_context():
    clock = DeterministicVirtualClock(datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC))
    id_factory = DeterministicIdFactory(scenario_id="test", scenario_version=1, seed=42)
    return RunContext(
        run_id=uuid.uuid4(),
        scenario_id="test",
        scenario_version=1,
        seed=42,
        clock=clock,
        id_factory=id_factory,
        tool_call_limit=5,
        time_limit_seconds=60,
        correlation_id="c1",
        scenario_digest="0" * 64,
        trajectory_digest="0" * 64,
    )


def test_model_tool_calling_agent_execution_loop():
    task = AgentTask(
        task_id="t1",
        scenario_id="s1",
        public_request="What is the status of AS142?",
        allowed_tools=["flight.get_status"],
    )

    prompt_policy = get_default_prompt_policy()
    registry = build_default_registry()
    provider = FixtureFlightProvider()
    clock = DeterministicVirtualClock(datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC))
    journal = HashChainJournal()
    executor = ToolExecutor(registry=registry, clock=clock, journal=journal, provider=provider)
    context0 = _make_context()

    args = {"flight_id": "AS142", "operating_day": "2026-07-28"}
    tool_call_id = str(context0.id_factory.next(record_type="tool_call", sequence=0))
    tc0 = ModelToolCall(call_id=tool_call_id, tool_name="flight.get_status", arguments=args)
    resp0 = ModelResponse(
        role="assistant", content=None, tool_calls=[tc0], finish_reason="tool_calls"
    )
    resp1 = ModelResponse(
        role="assistant", content="Flight AS142 is on time.", finish_reason="stop"
    )

    # Pass 1: Record exact ModelRequests generated by ModelToolCallingAgent
    recorded_requests: list[ModelRequest] = []

    class CapturingModelClient:
        provider = "replay"
        model_id = "gpt-4o-mini"

        def reset(self):
            recorded_requests.clear()

        async def create_completion(self, request: ModelRequest) -> ModelResponse:
            recorded_requests.append(request)
            if request.turn_index == 0:
                return resp0
            return resp1

    capture_agent = ModelToolCallingAgent(
        model_client=CapturingModelClient(),
        prompt_policy=prompt_policy,
    )
    asyncio.run(
        capture_agent.execute(
            task=task,
            executor=executor,
            state=StateSnapshot(),
            context=context0,
        )
    )

    assert len(recorded_requests) == 2

    # Pass 2: Replay using exact captured requests for guaranteed SHA-256 fingerprint matching
    ex0 = ModelExchange(
        turn_index=0,
        request=recorded_requests[0],
        response=resp0,
        request_fingerprint=recorded_requests[0].canonical_fingerprint(),
        response_digest=resp0.canonical_digest(),
    )
    ex1 = ModelExchange(
        turn_index=1,
        request=recorded_requests[1],
        response=resp1,
        request_fingerprint=recorded_requests[1].canonical_fingerprint(),
        response_digest=resp1.canonical_digest(),
    )

    replay_client = ReplayModelClient([ex0, ex1])
    replay_agent = ModelToolCallingAgent(model_client=replay_client, prompt_policy=prompt_policy)

    exec_context = _make_context()
    res = asyncio.run(
        replay_agent.execute(
            task=task,
            executor=executor,
            state=StateSnapshot(),
            context=exec_context,
        )
    )

    assert res.stop_reason == AgentStopReason.COMPLETED, f"Warnings: {res.warnings}"
    assert res.tool_call_count == 1
    assert res.final_response == "Flight AS142 is on time."
